#! /usr/bin/env python3
"""update_terminal

Usage:
    update_terminal <IDs> <HOSTSTATE> <STATETYPE> <HOSTATTEMPT>
"""

from docopt import docopt
from homeinfo.terminals.db import Terminal

options = docopt(__doc__)

if __name__ == '__main__':
    ids = options['<IDs>']
    tid, cid = [int(i) for i in ids.split('.')]
    state = options['<HOSTSTATE>']
    typ = options['<STATETYPE>']
    attempt = int(options['<HOSTATTEMPT>'])

    db_state = ' '.join([state, typ, str(attempt)])

    terminal = Terminal.by_ids(cid, tid)
    terminal.status = db_state
    terminal.save()
