#!/usr/bin/python3
"""chksync.

    Checks application status for the respective terminal.

Usage:
    chksync <id> [options]

Options:
    --help, -h      Show this page.
"""
from sys import exit    # pylint: disable=W0622

from docopt import docopt

from syslib import script
from terminallib import System, RemoteController


USER = 'termgr'
KEYFILE = '/var/lib/nagios/.ssh/terminals'
SYSTEMCTL = '/usr/bin/systemctl'
UNIT = 'application.service'


@script
def main(options):
    """Runs the application check."""

    try:
        system = System[options['<id>']]
    except ValueError:
        print('Invalid system ID.')
        exit(4)

    ctrl = RemoteController(USER, system, keyfile=KEYFILE)
    enabled = ctrl.execute(SYSTEMCTL, 'is-enabled', UNIT)
    running = ctrl.execute(SYSTEMCTL, 'is-active', UNIT)

    if 255 in {enabled.returncode, running.returncode}:
        print('Cannot connect to system.')
        exit(3)

    exit_code = min(enabled.returncode, 1) + min(running.returncode, 1)

    if exit_code == 0:
        print('Application is up and running.')
    elif exit_code == 1:
        if enabled:
            print('Application is not enabled but running.')
        elif running:
            print('Application is enabled but not running.')
        else:
            print('ERROR IN SCRIPT.')
    elif exit_code == 2:
        print('Application is neither enabled, nor running.')
    else:
        print('ERROR IN SCRIPT.')

    exit(exit_code)


if __name__ == '__main__':
    main(docopt(__doc__))
