#! /usr/bin/env python3
"""Checks statistics for the respective terminal

Usage:
    chkstats <tid> <cid>
"""

from datetime import datetime, timedelta

from docopt import docopt

from homeinfo.terminals.orm import AccessStats


if __name__ == '__main__':
    options = docopt(__doc__)
    tid = options['<tid>']
    cid = options['<cid>']
    try:
        tid = int(tid)
    except ValueError:
        print('Invalid terminal ID: {0}'.format(tid))
        exit(4)
    else:
        try:
            cid = int(cid)
        except ValueError:
            print('Invalid customer ID: {0}'.format(tid))
            exit(5)
        else:
            stats = AccessStats.select().where(
                (AccessStats.customer == cid) &
                (AccessStats.tid == tid))
            now = datetime.now()
            last5days = timedelta(days=5)
            last9days = timedelta(days=9)
            if [d for d in (now - s.timestamp for s in stats) if
                    d <= last5days]:
                print('OK')
                exit(0)  # ok
            elif [d for d in (now - s.timestamp for s in stats) if
                    d <= last9days]:
                print('More than five days no action!')
                exit(1)  # warning
            else:
                print('More than nine days no action!')
                exit(2)  # critical
