#! /usr/bin/env python3
"""Checks statistics for the respective terminal

Usage:
    chkstats <terminal_ident>
"""

from sys import stderr
from datetime import datetime, timedelta

from docopt import docopt

from homeinfo.terminals.orm import AccessStats


if __name__ == '__main__':
    options = docopt(__doc__)
    terminal_ident = options['<terminal_ident>']
    try:
        tid, cid = terminal_ident.split('.')
    except ValueError:
        print('Invalid terminal identifier: {0}'.format(terminal_ident),
              file=stderr)
        exit(3)
    else:
        try:
            tid = int(tid)
        except ValueError:
            print('Invalid terminal ID: {0}'.format(tid), file=stderr)
            exit(4)
        else:
            try:
                cid = int(cid)
            except ValueError:
                print('Invalid customer ID: {0}'.format(tid), file=stderr)
                exit(5)
            else:
                latest = None
                for stat in AccessStats.select().where(
                        (AccessStats.customer == cid) &
                        (AccessStats.tid == tid)):
                    if latest is None:
                        latest = stat.timestamp
                    else:
                        if latest > stat.timestamp:
                            latest = stat.timestamp
                if latest is None:
                    print('Never', file=stderr)
                    exit(2)
                else:
                    now = datetime.now()
                    if now - latest > timedelta(hours=72):
                        print(latest, file=stderr)
                        exit(2)
                    elif now - latest > timedelta(hours=24):
                        print(latest, file=stderr)
                        exit(1)
                    else:
                        print(latest)
                        exit(0)
