#! /usr/bin/env python3
"""Generates bind9 configuration for HOMEINFO's VPN networks."""

from subprocess import CalledProcessError, check_call
from sys import stderr, exit as exit_

from fancylog import TTYAnimator
from syslib import script
from terminallib import VPNUnconfiguredError, Terminal


__all__ = [
    'DNS_TEMPLATE',
    'DNS_CONFIG',
    'RECORD',
    'LOCAL_HOSTS_LIST',
    'management_hosts',
    'terminal_hosts']

SYSTEMCTL = '/bin/systemctl'
DNS_TEMPLATE = '/usr/local/etc/homeinfo.intranet.zone.temp'
LOCAL_HOSTS_LIST = '/usr/local/etc/local_hosts'
DNS_CONFIG = '/etc/bind/homeinfo.intranet.zone'
RECORD = '{}\tIN\tA\t{}'


def management_hosts():
    """Renders management network hosts."""

    yield ';# Management network hosts\n'

    with open(LOCAL_HOSTS_LIST, 'r') as local_hosts_list:
        for record in filter(
                lambda record: record and not record.startswith('#'),
                map(lambda record: record.strip(), local_hosts_list)):
            yield RECORD.format(*record.split())


def terminal_hosts():
    """Renders terminal network hosts."""

    yield ';# Terminal network hosts\n'

    for terminal in Terminal:
        try:
            ipv4addr = terminal.ipv4addr
        except VPNUnconfiguredError:
            print('Terminal {} has no VPN configuration.'.format(terminal),
                  file=stderr)
        else:
            yield RECORD.format(str(terminal), ipv4addr)


@script
def main():
    """Runs generates the confi files."""

    with open(DNS_TEMPLATE, 'r') as temp:
        template = temp.read()

    config = template.format(
        file=__file__,
        management='\n'.join(management_hosts()),
        terminals='\n'.join(terminal_hosts()))

    with open(DNS_CONFIG, 'w') as dns_cfg:
        dns_cfg.write(config)

    with TTYAnimator('Restarting bind9 service') as anim:
        try:
            check_call([SYSTEMCTL, 'restart', 'bind9.service'])
        except CalledProcessError:
            anim.result = False
            return 1
        else:
            anim.result = True
            return 0


if __name__ == '__main__':
    exit_(main())

