#! /usr/bin/env python3
#
#  This file is part of the python3 package "homeinfo.terminals"
#
#  (C) 2016: HOMEINFO - Digitale Informationssysteme GmbH
#
#  Maintainer: Richard Neumann <r dot neumann at homeinfo period de>
#
#####################################################################
"""Checks statistics for the respective terminal

Usage:
    chkstats <tid> <cid> [options]

Options:
    --warning=<days>, -w    Warning time period in days [default: 5].
    --critical=<days>, -c   Critical time period in days [default: 9].
"""
from gc import collect
from datetime import datetime, timedelta

from peewee import DoesNotExist

from homeinfo.terminals.orm import Terminal, Statistics


if __name__ == '__main__':
    from docopt import docopt

    options = docopt(__doc__)
    tid = options['<tid>']
    cid = options['<cid>']
    warning = options['--warning']
    critical = options['--critical']

    try:
        tid = int(tid)
    except ValueError:
        print('Invalid terminal ID: {}'.format(tid))
        exit(4)

    try:
        cid = int(cid)
    except ValueError:
        print('Invalid customer ID: {}'.format(tid))
        exit(5)

    try:
        warning = int(warning)
    except ValueError:
        print('Invalid amout of warning days: {}'.format(warning))
        exit(6)
    else:
        warning_delta = timedelta(days=warning)

    try:
        critical = int(critical)
    except ValueError:
        print('Invalid amout of critical days: {}'.format(critical))
        exit(7)
    else:
        critical_delta = timedelta(days=critical)

    latest = None

    for stat in Statistics.select().where(
            (Statistics.customer == cid) &
            (Statistics.tid == tid)):
        print('debug')

        if latest is None:
            latest = stat.timestamp
        else:
            if stat.timestamp > latest:
                latest = stat.timestamp

        collect()

    now = datetime.now()

    if latest is None:
        try:
            terminal = Terminal.by_ids(cid, tid)
        except DoesNotExist:
            print('No such terminal.')
            exit(2)
        else:
            if terminal.deployed is None:
                print('Terminal is not deployed.')
                exit(1)
            else:
                last = terminal.deployed
                print('never')
    else:
        print(last)

    if now - last <= warning_delta:
        exit(0)  # ok
    elif now - last <= critical_delta:
        exit(1)  # warning
    else:
        exit(2)  # critical
