#! /usr/bin/env python3
#
#  This file is part of the python3 package "homeinfo.terminals"
#
#  (C) 2016: HOMEINFO - Digitale Informationssysteme GmbH
#
#  Maintainer: Richard Neumann <r dot neumann at homeinfo period de>
#
#####################################################################
"""Updates latest statistics"""

from homeinfo.terminals.orm import LatestStats


if __name__ == '__main__':
    LatestStats.refresh()
