#! /usr/bin/env python3
"""Terminal database utility

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    termutil (list | ls) terminals [<expr> [(--deployed | --undeployed)] \
[(--testing | --productive)]]
    termutil (list | ls) (class | os | domains)
    termutil find <street> [<house_number>] [--annotation=<annotation>] \
[--index=<n>]

Options:
    --deployed                  Only print deployed terminals.
    --undeployed                Only print undeployed terminals.
    --testing                   Only print testing terminals.
    --productive                Only print productive terminals.
    --index=<n>                 On ambiguous results, use the nth.
    --annotation=<annotation>   Consider the respective location annotation.
"""
from docopt import docopt

from homeinfo.terminals.util import TerminalUtil, ClassUtil, OSUtil, DomainUtil


if __name__ == '__main__':
    options = docopt(__doc__)

    if options['list'] or options['ls']:
        expr = options['<expr>']
        terminals = options['terminals']

        if terminals:
            deployed = options['--deployed']
            undeployed = options['--undeployed']

            if not deployed and not undeployed:
                deployed = True
                undeployed = True

            testing = options['--testing']
            productive = options['--productive']

            if not testing and not productive:
                testing = True
                productive = True

            utl = TerminalUtil(expr, deployed, undeployed, testing, productive)
            print(str(utl))
        elif options['class']:
            utl = ClassUtil()
            print(str(utl))
        elif options['os']:
            utl = OSUtil()
            print(str(utl))
        elif options['domains']:
            utl = DomainUtil()
            print(str(utl))
    elif options['find']:
        if TerminalUtil.get(
                options['<street>'],
                options['<house_number>'],
                options['--annotation']):
            exit(0)
        else:
            exit(1)
