#! /usr/bin/env python3
"""Terminal database utility

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    termutil (list-terminals | ls) [<expr> [(--deployed | --undeployed)] \
[(--testing | --productive)]] [--omit-header]
    termutil list-class
    termutil list-os
    termutil list-domains
    termutil find <street> [<house_number>] [--annotation=<annotation>] \
[--index=<n>]

Options:
    --deployed                  Only print deployed terminals.
    --undeployed                Only print undeployed terminals.
    --testing                   Only print testing terminals.
    --productive                Only print productive terminals.
    --omit-header               Do not print the column header.
    --index=<n>                 On ambiguous results, use the nth.
    --annotation=<annotation>   Consider the respective location annotation.
"""
from docopt import docopt

from homeinfo.terminals.util import TerminalUtil, ClassUtil, OSUtil, DomainUtil


if __name__ == '__main__':
    options = docopt(__doc__)

    if options['list-terminals'] or options['ls']:
        expr = options['<expr>']
        deployed = options['--deployed']
        undeployed = options['--undeployed']

        if not deployed and not undeployed:
            deployed = True
            undeployed = True

        testing = options['--testing']
        productive = options['--productive']
        omit_header = options['--omit-header']

        if not testing and not productive:
            testing = True
            productive = True

        utl = TerminalUtil(expr, deployed, undeployed, testing, productive)

        if not omit_header:
            print(utl.header)

        print(str(utl))
    elif options['list-class']:
        utl = ClassUtil()
        print(str(utl))
    elif options['list-os']:
        utl = OSUtil()
        print(str(utl))
    elif options['list-domains']:
        utl = DomainUtil()
        print(str(utl))
    elif options['find']:
        if options['--index'] is None:
            index = None
        else:
            index = int(options['--index'])

        if TerminalUtil.get(
                options['<street>'],
                options['<house_number>'],
                options['--annotation'],
                index=index):
            exit(0)
        else:
            exit(1)
